//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasib.PTM.API.ReportTemplate {
    
    public partial class HasibFooter : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "Hasib.WIM.API.ReportTemplate.HasibFooter.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.line1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("line1");
            this.panel3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPanel>("panel3");
            this.Footer_PhoneLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Footer_PhoneLbl");
            this.Footer_Phone = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Footer_Phone");
            this.Footer_Website = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Footer_Website");
            this.Footer_WebsiteLbl = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Footer_WebsiteLbl");
            this.Page = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Page");
            this.pageInfo1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPageInfo>("pageInfo1");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.XRLine line1;
        private DevExpress.XtraReports.UI.XRPanel panel3;
        private DevExpress.XtraReports.UI.XRLabel Footer_PhoneLbl;
        private DevExpress.XtraReports.UI.XRLabel Footer_Phone;
        private DevExpress.XtraReports.UI.XRLabel Footer_Website;
        private DevExpress.XtraReports.UI.XRLabel Footer_WebsiteLbl;
        private DevExpress.XtraReports.UI.XRLabel Page;
        private DevExpress.XtraReports.UI.XRPageInfo pageInfo1;
    }
}
