//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasib.SSM.API.ReportTemplate {
    
    public partial class HasibHeader : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "Hasib.WIM.API.ReportTemplate.HasibHeader.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.xrLine2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine2");
            this.HasibHeader_CompanyTitle1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("HasibHeader_CompanyTitle1");
            this.HasibHeader_CompanyTitle2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("HasibHeader_CompanyTitle2");
            this.HasibHeader_CompanyTitle3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("HasibHeader_CompanyTitle3");
            this.Header_Module = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Header_Module");
            this.label5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label5");
            this.Header_EmployeeTxt = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Header_EmployeeTxt");
            this.Header_Employee = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Header_Employee");
            this.Header_Date = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Header_Date");
            this.HasibHeader_OrganizationHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("HasibHeader_OrganizationHeader");
            this.Header_Title = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("Header_Title");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.XRLine xrLine2;
        private DevExpress.XtraReports.UI.XRLabel HasibHeader_CompanyTitle1;
        private DevExpress.XtraReports.UI.XRLabel HasibHeader_CompanyTitle2;
        private DevExpress.XtraReports.UI.XRLabel HasibHeader_CompanyTitle3;
        private DevExpress.XtraReports.UI.XRLabel Header_Module;
        private DevExpress.XtraReports.UI.XRLabel label5;
        private DevExpress.XtraReports.UI.XRLabel Header_EmployeeTxt;
        private DevExpress.XtraReports.UI.XRLabel Header_Employee;
        private DevExpress.XtraReports.UI.XRLabel Header_Date;
        private DevExpress.XtraReports.UI.XRPictureBox HasibHeader_OrganizationHeader;
        private DevExpress.XtraReports.UI.XRLabel Header_Title;
    }
}
